name: TransitCard
version: '${project.version}'
main: me.andrej123456789.transitcard.TransitCard
api-version: '1.19'

libraries:
  - com.moandjiezana.toml:toml4j:0.7.2

commands:
  buy_transit:
    description: "Buy transit card for [transit X]"
    usage: "/buy_transit (transit) [hours]"
    permission: transit_card.buy
    permission-message: "&c[TransitCard] You don't have permission to use this command!"
