# Do you want to not give piece of paper to players
electronic_card = true

# Do you want to give players spyglass for easier signs reading
give_spyglass = true

[prices]
    bus = 0.5
    cable_car = 1.5
    ferry = 2.0
    metro = 1.0
    monorail = 1.0
    tram = 1.0
